"""add edit/reportes/bloqueos/eliminado_por_usuario

Revision ID: 77660891896d
Revises: 9b0499c257bc
Create Date: 2026-08-11 14:59:28.222865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77660891896d'
down_revision = '9b0499c257bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bloqueador_id', sa.Integer(), nullable=False),
    sa.Column('bloqueado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bloqueado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['bloqueador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bloqueador_id', 'bloqueado_id', name='uq_bloqueador_bloqueado')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reportante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_objetivo', sa.String(length=20), nullable=False),
    sa.Column('objetivo_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reportante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('editado', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'eliminado_por_usuario', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('eliminado_por_usuario')

    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_column('editado')

    op.drop_table('reportes')
    op.drop_table('bloqueos')
    # ### end Alembic commands ###
